version: '3.9' 

services:
  app: 
    build: . 
    image: astro-web:dev 
    ports:
      - "3000:3000" 
    volumes:
      - .:/app 
      - /app/node_modules 
    command: yarn dev --host 0.0.0.0
